/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod';



export const getRoomParams = zod.object({
  "id": zod.number()
})

export const updateRoomParams = zod.object({
  "id": zod.number()
})

export const updateRoomBodyTypeRegExp = new RegExp('Single|Double|Twin|Family|Suite');
export const updateRoomBodyRoomPriceMax = 999;


export const updateRoomBody = zod.object({
  "roomid": zod.number().optional(),
  "roomName": zod.string(),
  "type": zod.string().regex(updateRoomBodyTypeRegExp),
  "accessible": zod.boolean().optional(),
  "image": zod.string().optional(),
  "description": zod.string().optional(),
  "features": zod.array(zod.string()).optional(),
  "roomPrice": zod.number().min(1).max(updateRoomBodyRoomPriceMax).optional()
})

export const deleteRoomParams = zod.object({
  "id": zod.number()
})

export const createRoomBodyTypeRegExp = new RegExp('Single|Double|Twin|Family|Suite');
export const createRoomBodyRoomPriceMax = 999;


export const createRoomBody = zod.object({
  "roomid": zod.number().optional(),
  "roomName": zod.string(),
  "type": zod.string().regex(createRoomBodyTypeRegExp),
  "accessible": zod.boolean().optional(),
  "image": zod.string().optional(),
  "description": zod.string().optional(),
  "features": zod.array(zod.string()).optional(),
  "roomPrice": zod.number().min(1).max(createRoomBodyRoomPriceMax).optional()
})

