/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Room {
  roomid?: number;
  roomName: string;
  /** @pattern Single|Double|Twin|Family|Suite */
  type: string;
  accessible?: boolean;
  image?: string;
  description?: string;
  features?: string[];
  /**
   * @minimum 1
   * @maximum 999
   */
  roomPrice?: number;
}
