/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BookingDates } from './bookingDates';

export interface Booking {
  bookingid?: number;
  /** @minimum 1 */
  roomid?: number;
  /**
   * @minLength 3
   * @maxLength 18
   */
  firstname: string;
  /**
   * @minLength 3
   * @maxLength 30
   */
  lastname: string;
  depositpaid: boolean;
  email: string;
  /**
   * @minLength 11
   * @maxLength 21
   */
  phone: string;
  bookingdates?: BookingDates;
}
