/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Booking } from './booking';

export interface CreatedBooking {
  bookingid?: number;
  booking?: Booking;
}
