/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod';



export const getBookingParams = zod.object({
  "id": zod.number()
})

export const updateBookingParams = zod.object({
  "id": zod.number()
})

export const updateBookingBodyFirstnameMin = 3;

export const updateBookingBodyFirstnameMax = 18;
export const updateBookingBodyLastnameMin = 3;

export const updateBookingBodyLastnameMax = 30;
export const updateBookingBodyPhoneMin = 11;

export const updateBookingBodyPhoneMax = 21;


export const updateBookingBody = zod.object({
  "bookingid": zod.number().optional(),
  "roomid": zod.number().min(1).optional(),
  "firstname": zod.string().min(updateBookingBodyFirstnameMin).max(updateBookingBodyFirstnameMax),
  "lastname": zod.string().min(updateBookingBodyLastnameMin).max(updateBookingBodyLastnameMax),
  "depositpaid": zod.boolean(),
  "email": zod.string(),
  "phone": zod.string().min(updateBookingBodyPhoneMin).max(updateBookingBodyPhoneMax),
  "bookingdates": zod.object({
  "checkin": zod.string().date(),
  "checkout": zod.string().date()
}).optional()
})

export const deleteBookingParams = zod.object({
  "id": zod.number()
})

export const getBookingsQueryParams = zod.object({
  "roomid": zod.string().optional()
})

export const createBookingBodyFirstnameMin = 3;

export const createBookingBodyFirstnameMax = 18;
export const createBookingBodyLastnameMin = 3;

export const createBookingBodyLastnameMax = 30;
export const createBookingBodyPhoneMin = 11;

export const createBookingBodyPhoneMax = 21;


export const createBookingBody = zod.object({
  "bookingid": zod.number().optional(),
  "roomid": zod.number().min(1).optional(),
  "firstname": zod.string().min(createBookingBodyFirstnameMin).max(createBookingBodyFirstnameMax),
  "lastname": zod.string().min(createBookingBodyLastnameMin).max(createBookingBodyLastnameMax),
  "depositpaid": zod.boolean(),
  "email": zod.string(),
  "phone": zod.string().min(createBookingBodyPhoneMin).max(createBookingBodyPhoneMax),
  "bookingdates": zod.object({
  "checkin": zod.string().date(),
  "checkout": zod.string().date()
}).optional()
})

export const getSummariesQueryParams = zod.object({
  "roomid": zod.string()
})

