/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiReportsId200Data } from './getApiReportsId200Data';

export type GetApiReportsId200 = {
  success?: boolean;
  data?: GetApiReportsId200Data;
};
