/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRoomsId200DataStatus = typeof GetApiRoomsId200DataStatus[keyof typeof GetApiRoomsId200DataStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiRoomsId200DataStatus = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  MAINTENANCE: 'MAINTENANCE',
} as const;
