/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBranding200Data } from './getApiBranding200Data';

export type GetApiBranding200 = {
  success?: boolean;
  data?: GetApiBranding200Data;
};
