/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBookingsId200Data } from './getApiBookingsId200Data';

export type GetApiBookingsId200 = {
  success?: boolean;
  data?: GetApiBookingsId200Data;
};
