/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMessages200DataItem } from './getApiMessages200DataItem';

export type GetApiMessages200 = {
  success?: boolean;
  data?: GetApiMessages200DataItem[];
};
