/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiRooms200DataItem } from './getApiRooms200DataItem';

export type GetApiRooms200 = {
  success?: boolean;
  data?: GetApiRooms200DataItem[];
};
