/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type GetApiReports200DataItemType = typeof GetApiReports200DataItemType[keyof typeof GetApiReports200DataItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiReports200DataItemType = {
  OCCUPANCY: 'OCCUPANCY',
  REVENUE: 'REVENUE',
  MAINTENANCE: 'MAINTENANCE',
} as const;
