/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiReports200DataItem } from './getApiReports200DataItem';

export type GetApiReports200 = {
  success?: boolean;
  data?: GetApiReports200DataItem[];
};
