/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiReportsId200DataType } from './getApiReportsId200DataType';

export type GetApiReportsId200Data = {
  id?: string;
  title?: string;
  content?: string;
  type?: GetApiReportsId200DataType;
  createdAt?: string;
  updatedAt?: string;
};
