/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRooms200DataItemType = typeof GetApiRooms200DataItemType[keyof typeof GetApiRooms200DataItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiRooms200DataItemType = {
  STANDARD: 'STANDARD',
  DELUXE: 'DELUXE',
  SUITE: 'SUITE',
} as const;
