/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBookings200DataItem } from './getApiBookings200DataItem';

export type GetApiBookings200 = {
  success?: boolean;
  data?: GetApiBookings200DataItem[];
};
