/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiRoomsId200DataType } from './getApiRoomsId200DataType';
import type { GetApiRoomsId200DataStatus } from './getApiRoomsId200DataStatus';

export type GetApiRoomsId200Data = {
  id?: string;
  number?: string;
  type?: GetApiRoomsId200DataType;
  price?: number;
  capacity?: number;
  amenities?: string[];
  status?: GetApiRoomsId200DataStatus;
};
