/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRooms200DataItemStatus = typeof GetApiRooms200DataItemStatus[keyof typeof GetApiRooms200DataItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiRooms200DataItemStatus = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  MAINTENANCE: 'MAINTENANCE',
} as const;
