/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiRooms200DataItemType } from './getApiRooms200DataItemType';
import type { GetApiRooms200DataItemStatus } from './getApiRooms200DataItemStatus';

export type GetApiRooms200DataItem = {
  id?: string;
  number?: string;
  type?: GetApiRooms200DataItemType;
  price?: number;
  capacity?: number;
  amenities?: string[];
  status?: GetApiRooms200DataItemStatus;
};
