/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiReports200DataItemType } from './getApiReports200DataItemType';

export type GetApiReports200DataItem = {
  id?: string;
  title?: string;
  content?: string;
  type?: GetApiReports200DataItemType;
  createdAt?: string;
  updatedAt?: string;
};
