/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiRoomsId200Data } from './getApiRoomsId200Data';

export type GetApiRoomsId200 = {
  success?: boolean;
  data?: GetApiRoomsId200Data;
};
