/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMessagesId200Data } from './getApiMessagesId200Data';

export type GetApiMessagesId200 = {
  success?: boolean;
  data?: GetApiMessagesId200Data;
};
