/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBookingsId200DataStatus } from './getApiBookingsId200DataStatus';

export type GetApiBookingsId200Data = {
  id?: string;
  userId?: string;
  roomId?: string;
  checkIn?: string;
  checkOut?: string;
  status?: GetApiBookingsId200DataStatus;
  totalPrice?: number;
  createdAt?: string;
  updatedAt?: string;
};
