/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type GetApiRoomsId200DataType = typeof GetApiRoomsId200DataType[keyof typeof GetApiRoomsId200DataType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiRoomsId200DataType = {
  STANDARD: 'STANDARD',
  DELUXE: 'DELUXE',
  SUITE: 'SUITE',
} as const;
