/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthLogin200DataUser } from './postApiAuthLogin200DataUser';

export type PostApiAuthLogin200Data = {
  token?: string;
  user?: PostApiAuthLogin200DataUser;
};
