/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAuthRegister201DataRole = typeof PostApiAuthRegister201DataRole[keyof typeof PostApiAuthRegister201DataRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiAuthRegister201DataRole = {
  ROLE_USER: 'ROLE_USER',
} as const;
