/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type PostApiBookings201DataStatus = typeof PostApiBookings201DataStatus[keyof typeof PostApiBookings201DataStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiBookings201DataStatus = {
  PENDING: 'PENDING',
} as const;
