/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiReports201DataType } from './postApiReports201DataType';

export type PostApiReports201Data = {
  id?: string;
  title?: string;
  content?: string;
  type?: PostApiReports201DataType;
  createdAt?: string;
  updatedAt?: string;
};
