/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type PostApiAuthLogin200DataUserRole = typeof PostApiAuthLogin200DataUserRole[keyof typeof PostApiAuthLogin200DataUserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiAuthLogin200DataUserRole = {
  ROLE_USER: 'ROLE_USER',
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;
