/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type PostApiReports201DataType = typeof PostApiReports201DataType[keyof typeof PostApiReports201DataType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiReports201DataType = {
  OCCUPANCY: 'OCCUPANCY',
  REVENUE: 'REVENUE',
  MAINTENANCE: 'MAINTENANCE',
} as const;
