/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiBookings201Data } from './postApiBookings201Data';

export type PostApiBookings201 = {
  success?: boolean;
  data?: PostApiBookings201Data;
};
