/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthLogin200DataUserRole } from './postApiAuthLogin200DataUserRole';

export type PostApiAuthLogin200DataUser = {
  id?: string;
  username?: string;
  role?: PostApiAuthLogin200DataUserRole;
};
