/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiRoomsBodyType } from './postApiRoomsBodyType';

export type PostApiRoomsBody = {
  number: string;
  type: PostApiRoomsBodyType;
  price: number;
  capacity: number;
  amenities?: string[];
};
