/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiBookings201DataStatus } from './postApiBookings201DataStatus';

export type PostApiBookings201Data = {
  id?: string;
  userId?: string;
  roomId?: string;
  checkIn?: string;
  checkOut?: string;
  status?: PostApiBookings201DataStatus;
  totalPrice?: number;
  createdAt?: string;
  updatedAt?: string;
};
