/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthLogin200Data } from './postApiAuthLogin200Data';

export type PostApiAuthLogin200 = {
  success?: boolean;
  data?: PostApiAuthLogin200Data;
};
