/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiBrandingReset200Data } from './postApiBrandingReset200Data';

export type PostApiBrandingReset200 = {
  success?: boolean;
  data?: PostApiBrandingReset200Data;
};
