/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiBookingsId200Data } from './putApiBookingsId200Data';

export type PutApiBookingsId200 = {
  success?: boolean;
  data?: PutApiBookingsId200Data;
};
