/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type PutApiRoomsId200Data = {
  id?: string;
  number?: string;
  type?: string;
  price?: number;
  capacity?: number;
  amenities?: string[];
  status?: string;
};
