/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiRoomsId200Data } from './putApiRoomsId200Data';

export type PutApiRoomsId200 = {
  success?: boolean;
  data?: PutApiRoomsId200Data;
};
