/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */

export type PutApiBookingsId200DataStatus = typeof PutApiBookingsId200DataStatus[keyof typeof PutApiBookingsId200DataStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiBookingsId200DataStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
} as const;
