/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiMessagesId200Data } from './putApiMessagesId200Data';

export type PutApiMessagesId200 = {
  success?: boolean;
  data?: PutApiMessagesId200Data;
};
