/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiRoomsIdBodyType } from './putApiRoomsIdBodyType';
import type { PutApiRoomsIdBodyStatus } from './putApiRoomsIdBodyStatus';

export type PutApiRoomsIdBody = {
  number?: string;
  type?: PutApiRoomsIdBodyType;
  price?: number;
  capacity?: number;
  amenities?: string[];
  status?: PutApiRoomsIdBodyStatus;
};
