/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiBranding200Data } from './putApiBranding200Data';

export type PutApiBranding200 = {
  success?: boolean;
  data?: PutApiBranding200Data;
};
