/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod';



export const validateTokenBody = zod.object({
  "token": zod.string()
})

export const clearTokenBody = zod.object({
  "token": zod.string().optional()
})

export const createTokenBody = zod.object({
  "username": zod.string().optional(),
  "password": zod.string().optional()
})

