/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Login user
 */
export const postApiAuthLoginBody = zod.object({
  "username": zod.string(),
  "password": zod.string()
})

export const postApiAuthLoginResponse = zod.object({
  "success": zod.boolean().optional(),
  "data": zod.object({
  "token": zod.string().optional(),
  "user": zod.object({
  "id": zod.string().optional(),
  "username": zod.string().optional(),
  "role": zod.enum(['ROLE_USER', 'ROLE_ADMIN']).optional()
}).optional()
}).optional()
})

/**
 * @summary Register new user
 */
export const postApiAuthRegisterBody = zod.object({
  "username": zod.string(),
  "password": zod.string(),
  "email": zod.string()
})

/**
 * @summary Logout user
 */
export const postApiAuthLogoutResponse = zod.object({
  "success": zod.boolean().optional()
})

