/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Get all reports
 */
export const getApiReportsResponse = zod.object({
  "success": zod.boolean().optional(),
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "title": zod.string().optional(),
  "content": zod.string().optional(),
  "type": zod.enum(['OCCUPANCY', 'REVENUE', 'MAINTENANCE']).optional(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
})).optional()
})

/**
 * @summary Create new report (admin only)
 */
export const postApiReportsBody = zod.object({
  "title": zod.string(),
  "content": zod.string(),
  "type": zod.enum(['OCCUPANCY', 'REVENUE', 'MAINTENANCE'])
})

/**
 * @summary Get report by ID
 */
export const getApiReportsIdParams = zod.object({
  "id": zod.string().describe('Report ID')
})

export const getApiReportsIdResponse = zod.object({
  "success": zod.boolean().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "title": zod.string().optional(),
  "content": zod.string().optional(),
  "type": zod.enum(['OCCUPANCY', 'REVENUE', 'MAINTENANCE']).optional(),
  "createdAt": zod.string().datetime().optional(),
  "updatedAt": zod.string().datetime().optional()
}).optional()
})

/**
 * @summary Delete report (admin only)
 */
export const deleteApiReportsIdParams = zod.object({
  "id": zod.string().describe('Report ID')
})

export const deleteApiReportsIdResponse = zod.object({
  "success": zod.boolean().optional(),
  "message": zod.string().optional()
})

