/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Restful Booker Platform API
 * API documentation for the Restful Booker Platform
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';



/**
 * @summary Get all rooms
 */
export const getApiRoomsResponse = zod.object({
  "success": zod.boolean().optional(),
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "number": zod.string().optional(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']).optional(),
  "price": zod.number().optional(),
  "capacity": zod.number().optional(),
  "amenities": zod.array(zod.string()).optional(),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']).optional()
})).optional()
})

/**
 * @summary Create new room (admin only)
 */
export const postApiRoomsBody = zod.object({
  "number": zod.string(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']),
  "price": zod.number(),
  "capacity": zod.number(),
  "amenities": zod.array(zod.string()).optional()
})

/**
 * @summary Get room by ID
 */
export const getApiRoomsIdParams = zod.object({
  "id": zod.string().describe('Room ID')
})

export const getApiRoomsIdResponse = zod.object({
  "success": zod.boolean().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "number": zod.string().optional(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']).optional(),
  "price": zod.number().optional(),
  "capacity": zod.number().optional(),
  "amenities": zod.array(zod.string()).optional(),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']).optional()
}).optional()
})

/**
 * @summary Update room (admin only)
 */
export const putApiRoomsIdParams = zod.object({
  "id": zod.string().describe('Room ID')
})

export const putApiRoomsIdBody = zod.object({
  "number": zod.string().optional(),
  "type": zod.enum(['STANDARD', 'DELUXE', 'SUITE']).optional(),
  "price": zod.number().optional(),
  "capacity": zod.number().optional(),
  "amenities": zod.array(zod.string()).optional(),
  "status": zod.enum(['AVAILABLE', 'OCCUPIED', 'MAINTENANCE']).optional()
})

export const putApiRoomsIdResponse = zod.object({
  "success": zod.boolean().optional(),
  "data": zod.object({
  "id": zod.string().optional(),
  "number": zod.string().optional(),
  "type": zod.string().optional(),
  "price": zod.number().optional(),
  "capacity": zod.number().optional(),
  "amenities": zod.array(zod.string()).optional(),
  "status": zod.string().optional()
}).optional()
})

/**
 * @summary Delete room (admin only)
 */
export const deleteApiRoomsIdParams = zod.object({
  "id": zod.string().describe('Room ID')
})

export const deleteApiRoomsIdResponse = zod.object({
  "success": zod.boolean().optional(),
  "message": zod.string().optional()
})

